CREATE TABLE TB_ITEM(
    id INT AUTO_INCREMENT PRIMARY KEY,
    _name VARCHAR(255) NOT NULL,
    price INT DEFAULT 0 NOT NULl
);


CREATE TABLE TB_ORDER(
    id INT AUTO_INCREMENT PRIMARY KEY,
    item_id INT NOT NULL,
    qty INT NOT NULl,
    FOREIGN KEY (item_id) 
        REFERENCES TB_ITEM(id) 
        ON DELETE CASCADE 
        ON UPDATE CASCADE
);


CREATE TABLE TB_INVENTORY(
    id INT AUTO_INCREMENT PRIMARY KEY,    
    item_id INT NOT NULL,
    qty INT NOT NULL,
    _type CHAR(1) NOT NULl,

    FOREIGN KEY (item_id) REFERENCES TB_ITEM(id)
        ON DELETE CASCADE 
        ON UPDATE CASCADE
);

